#! /usr/bin/env python
from random import randint

import rospy
import actionlib
import tf2_ros
import tf2_geometry_msgs

from geometry_msgs.msg import Pose
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal

from multi_jackal_tutorials.msg import NavigateWaypointAction, NavigateWaypointGoal

from multi_jackal_tutorials.msg import InspectWaypointAction
from multi_jackal_tutorials.msg import InspectWaypointGoal
from multi_jackal_tutorials.msg import InspectWaypointFeedback
from multi_jackal_tutorials.msg import InspectWaypointResult

def transform_pose(input_pose, from_frame, to_frame):
    tf_buffer = tf2_ros.Buffer()
    listener = tf2_ros.TransformListener(tf_buffer)

    pose_stamped = tf2_geometry_msgs.PoseStamped()
    pose_stamped.pose = input_pose
    pose_stamped.header.frame_id = from_frame
    pose_stamped.header.stamp = rospy.Time(0)

    try:
        output_pose_stamped = tf_buffer.transform(pose_stamped, to_frame, rospy.Duration(2))
        return output_pose_stamped.pose

    except (tf2_ros.LookupException, tf2_ros.ConnectivityException, tf2_ros.ExtrapolationException):
        raise

class InspectWaypointActionServer(object):
    def __init__(self, name):
        # create messages that are used to publish feedback/result
        self._feedback = InspectWaypointFeedback()
        self._result = InspectWaypointResult()
        self._ns = rospy.get_namespace()
        self._action_name = name
        self._as = actionlib.SimpleActionServer(self._action_name, InspectWaypointAction, execute_cb=self.execute_cb, auto_start = False)

        self._as.start()

    def execute_cb(self, goal):
        # helper variables
        r = rospy.Rate(1)
        success = True
        param_name = "/Inspection_Waypoints/"+goal.waypoint
        pose_list = rospy.get_param(param_name)
        frame_id = rospy.get_param(self._ns+"jackal_velocity_controller/odom_frame_id")

        rospy.loginfo('%s will inspect %s' % (self._ns, goal.waypoint))

        print pose_list.keys()
        for pose_name in pose_list.keys():
            pose_goal = pose_list[pose_name]
            #print(pose_goal)

            current_pose_goal_in_map = Pose()

            current_pose_goal_in_map.position.x = pose_goal[0]
            current_pose_goal_in_map.position.y = pose_goal[1]
            current_pose_goal_in_map.position.z = pose_goal[2]

            current_pose_goal_in_map.orientation.x = pose_goal[3]
            current_pose_goal_in_map.orientation.y = pose_goal[4]
            current_pose_goal_in_map.orientation.z = pose_goal[5]
            current_pose_goal_in_map.orientation.w = pose_goal[6]

            current_pose_goal_in_odom = Pose()
            current_pose_goal_in_odom = transform_pose(current_pose_goal_in_map, "map", frame_id)

            #print(current_pose_goal_in_odom)

            client = actionlib.SimpleActionClient('move_base', MoveBaseAction)
            client.wait_for_server()
            mb_goal = MoveBaseGoal()

            mb_goal.target_pose.header.frame_id = frame_id
            mb_goal.target_pose.header.stamp = rospy.Time.now()
            mb_goal.target_pose.pose = current_pose_goal_in_odom

            client.send_goal(mb_goal)
            wait = client.wait_for_result()

        if success:
            self._result.success = 1
            rospy.loginfo('%s: Succeeded' % self._action_name)
            self._as.set_succeeded(self._result)

if __name__ == '__main__':
    rospy.init_node('tb1_Navigate')
    server = InspectWaypointActionServer(rospy.get_name())
    rospy.spin()
